comment_width = 100
condense_wildcard_suffixes = true
fn_single_line = true
force_multiline_blocks = false
format_strings = true
imports_granularity = "Crate"
imports_indent = "Block"
max_width = 100
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
struct_field_align_threshold = 30
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
