#!/bin/sh

printf '%s\n' \
  '`do-release-upgrade` is not supported on Pop!_OS.' \
  'Use `pop-upgrade release upgrade` instead.' \
  '' \
  'For more information, visit: https://support.system76.com/articles/upgrade-pop'