[package]
name = "pop-upgrade-gtk-ffi"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[build-dependencies]
cdylib-link-lines = "0.1"

[dependencies]
pop-upgrade-gtk = { path = "../" }
glib = "0.7.1"
gtk-sys = "0.8.0"
gtk = "0.6.0"

[lib]
name = "pop_upgrade_gtk"
crate-type = [ "cdylib" ]
