on:
  push:
    branches: [master]
  pull_request:

name: Continuous integration

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: install system dependencies
        run: sudo apt-get install libdbus-1-dev libparted-dev libgtk-3-dev libmount-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all
