on:
  push:
    branches: [master]
  pull_request:

name: Code Coverage

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:

      - name: install system dependencies
        run: sudo apt-get install libdbus-1-dev libparted-dev libgtk-3-dev libmount-dev

      - name: checkout source
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: --all-features --workspace

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
